_wandb:
    value:
        cli_version: 0.21.1
        e:
            sy5ha22wjglcegsytx2ow25n2yu5a1hl:
                args:
                    - --data-root
                    - /home/vhsingh/Parshvi_project/data/processed
                    - --out-dir
                    - /home/vhsingh/Parshvi_project/model_outputs/tabmlp_baseline_20250914_192441
                    - --epochs
                    - "140"
                    - --lr
                    - "1e-3"
                    - --wd
                    - "1e-4"
                    - --patience
                    - "18"
                    - --n-splits
                    - "5"
                    - --seed
                    - "42"
                    - --wandb
                    - --wandb-project
                    - Risk_Score
                    - --wandb-entity
                    - ved100-carnegie-mellon-university
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "236663791616"
                        used: "99669037056"
                email: vhsingh@andrew.cmu.edu
                executable: /home/vhsingh/miniconda3/envs/Research/bin/python
                git:
                    commit: 4fb83a8a9fbb82b4843fe30843249149a4aa3c1d
                    remote: https://github.com/VedantSingh-100/Risk-Score-Modelling.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-b349d8f4-c2a8-bd4b-2ed8-4678cc3093ad
                host: babel-0-31
                memory:
                    total: "1081484091392"
                os: Linux-5.14.0-503.40.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: -m src.models.train_baseline_mlp
                python: CPython 3.12.9
                root: /home/vhsingh/Parshvi_project
                slurm:
                    cluster_name: babel
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: atalwalk
                    job_cpus_per_node: "16"
                    job_end_time: "1757949877"
                    job_gid: "2700465"
                    job_gpus: "0"
                    job_id: "5460210"
                    job_name: risk_overnight
                    job_nodelist: babel-0-31
                    job_num_nodes: "1"
                    job_partition: general
                    job_qos: normal
                    job_start_time: "1757892277"
                    job_uid: "2700465"
                    job_user: vhsingh
                    jobid: "5460210"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: babel-0-31
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/vhsingh/Parshvi_project
                    submit_host: babel-3-17
                    task_pid: "50127"
                    tasks_per_node: "1"
                    topology_addr: babel-0-31
                    topology_addr_pattern: node
                    tres_per_task: cpu=16
                startedAt: "2025-09-15T00:50:25.433138Z"
                writerId: sy5ha22wjglcegsytx2ow25n2yu5a1hl
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": linux-x86_64
data_root:
    value: /home/vhsingh/Parshvi_project/data/processed
epochs:
    value: 140
lr:
    value: 0.001
n_features:
    value: 571
n_positives:
    value: 66
n_samples:
    value: 49389
n_splits:
    value: 5
out_dir:
    value: /home/vhsingh/Parshvi_project/model_outputs/tabmlp_baseline_20250914_192441
patience:
    value: 18
prevalence:
    value: 0.0013363299520136062
seed:
    value: 42
target:
    value: null
target_name:
    value: label
wandb:
    value: true
wandb_entity:
    value: ved100-carnegie-mellon-university
wandb_project:
    value: Risk_Score
wd:
    value: 0.0001
