_wandb:
    value:
        cli_version: 0.21.1
        e:
            c3ym56kdvq24ce4q6pdlupdexu1aj2xa:
                args:
                    - --data-root
                    - /home/vhsingh/Parshvi_project/data/processed
                    - --out-dir
                    - /home/vhsingh/Parshvi_project/model_outputs/fttr_20250915_001519
                    - --layers
                    - "4"
                    - --d-model
                    - "96"
                    - --heads
                    - "8"
                    - --ff-mult
                    - "2.0"
                    - --dropout
                    - "0.15"
                    - --attn-dropout
                    - "0.10"
                    - --feature-dropout
                    - "0.05"
                    - --epochs
                    - "160"
                    - --batch-size
                    - "256"
                    - --lr
                    - "1e-3"
                    - --weight-decay
                    - "1e-4"
                    - --warmup-ratio
                    - "0.06"
                    - --patience
                    - "20"
                    - --n-splits
                    - "5"
                    - --seed
                    - "42"
                    - --wandb-project
                    - Risk_Score_Transformer
                    - --wandb-run-name
                    - fttr_20250915_001519
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "236663791616"
                        used: "101522620416"
                email: vhsingh@andrew.cmu.edu
                executable: /home/vhsingh/miniconda3/envs/Research/bin/python
                git:
                    commit: 34aec8643fcf6e62a2108ddcc579c2aeefca630a
                    remote: https://github.com/VedantSingh-100/Risk-Score-Modelling.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-457a590e-5dab-960f-460a-0113d8fe3d97
                host: babel-0-27
                memory:
                    total: "1081486409728"
                os: Linux-5.14.0-503.40.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: -m src.models.train_fttransformer
                python: CPython 3.12.9
                root: /home/vhsingh/Parshvi_project
                slurm:
                    cluster_name: babel
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: atalwalk
                    job_cpus_per_node: "16"
                    job_end_time: "1757952908"
                    job_gid: "2700465"
                    job_gpus: "4"
                    job_id: "5460921"
                    job_name: ft_transformer
                    job_nodelist: babel-0-27
                    job_num_nodes: "1"
                    job_partition: general
                    job_qos: normal
                    job_start_time: "1757909708"
                    job_uid: "2700465"
                    job_user: vhsingh
                    jobid: "5460921"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: babel-0-27
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/vhsingh/Parshvi_project
                    submit_host: babel-3-17
                    task_pid: "2988538"
                    tasks_per_node: "1"
                    topology_addr: babel-0-27
                    topology_addr_pattern: node
                    tres_per_task: cpu=16
                startedAt: "2025-09-15T04:15:23.098322Z"
                writerId: c3ym56kdvq24ce4q6pdlupdexu1aj2xa
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 3
                - 13
                - 15
                - 16
            "4": 3.12.9
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": linux-x86_64
attn_dropout:
    value: 0.1
batch_size:
    value: 256
d_model:
    value: 96
data_root:
    value: /home/vhsingh/Parshvi_project/data/processed
disable_wandb:
    value: false
dropout:
    value: 0.15
epochs:
    value: 160
feature_dropout:
    value: 0.05
ff_mult:
    value: 2
grad_clip:
    value: 1
heads:
    value: 8
layers:
    value: 4
lr:
    value: 0.001
min_lr:
    value: 1e-06
n_splits:
    value: 5
out_dir:
    value: /home/vhsingh/Parshvi_project/model_outputs/fttr_20250915_001519
patience:
    value: 20
seed:
    value: 42
target:
    value: null
wandb_project:
    value: Risk_Score_Transformer
wandb_run_name:
    value: fttr_20250915_001519
warmup_ratio:
    value: 0.06
weight_decay:
    value: 0.0001
