# Training Configuration
# This file contains the key parameters used for model training

# Data paths
data:
  features_path: "data/processed/X_features.parquet"
  labels_path: "data/processed/y_label.csv"
  guard_file: "configs/guard_Set.txt"

# Feature engineering
feature_engineering:
  redundancy_threshold: 0.97  # Correlation threshold for redundancy pruning
  fill_rate_threshold: 0.85   # Minimum fill rate for feature inclusion
  
# Cross-validation
cross_validation:
  n_splits: 5
  shuffle: true
  random_seeds: [42, 202, 404, 808, 1337]

# Model parameters
models:
  logistic:
    penalty: "elasticnet"
    l1_ratio: 0.5
    C: 1.0
    max_iter: 5000
    solver: "saga"
  
  xgboost:
    objective: "binary:logistic"
    n_estimators: 5000
    learning_rate: 0.02
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.2
    early_stopping_rounds: 300
  
  lightgbm:
    objective: "binary"
    n_estimators: 5000
    learning_rate: 0.02
    num_leaves: 31
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.2
    early_stopping_rounds: 300

# Output paths
output:
  baselines_dir: "artifacts/reports/baselines"
  boosters_dir: "artifacts/reports/boosters"
